package com.swapit.domain.enums;

public enum SwapRequestStatus {
    CREATED,
    CONSENT_CONFIRMED,
    PHOTO_UPLOADED,
    INSPECTION_COMPLETED,
    PRE_VALUATION_READY,
    PRE_VALUATION_ACCEPTED,
    PRODUCT_SELECTED,
    BOOKING_CONFIRMED,
    INSTANT_CALL_REQUESTED,
    CREW_ASSIGNED,
    PICKUP_IN_PROGRESS,
    CREW_ARRIVED,
    DELIVERED_TO_EWASTE_HUB,
    REWARD_READY,
    DELIVERY_PREPARING,
    DELIVERY_SHIPPED,
    DELIVERY_COMPLETED,
    RE_REVIEW_REQUESTED,
    RE_REVIEW_COMPLETED,
    CREDIT_ISSUED,
    COMPLETED,
    CANCELLED
}
