package com.swapit.domain.enums;

public enum SwapRequestStatus {
    CREATED,
    PHOTO_UPLOADED,
    INSPECTION_COMPLETED,
    PRE_VALUATION_READY,
    PRE_VALUATION_ACCEPTED,
    BOOKING_CONFIRMED,
    CREW_ASSIGNED,
    PICKUP_IN_PROGRESS,
    PICKUP_COMPLETED,
    FINAL_VALUATION_READY,
    CREDIT_ISSUED,
    COMPLETED,
    CANCELLED
}

